routes/web.php
<?php

use App\Http\Controllers\BlogCategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\BookingValueController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\CommentsReplyController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\FormValueController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailTempleteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PollController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\FormCommentsController;
use App\Http\Controllers\FormCommentsReplyController;
use App\Http\Controllers\DashboardWidgetController;
use App\Http\Controllers\DocumentGenratorController;
use App\Http\Controllers\DocumentMenuController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FormTemplateController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\LoginSecurityController;
use App\Http\Controllers\PaymentGateway\MercadoController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\PaymentGateway\MollieController;
use App\Http\Controllers\NotificationsSettingController;
use App\Http\Controllers\PaymentGateway\PaytmController;
use App\Http\Controllers\PaymentGateway\PayUMoneyController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SmsController;
use App\Http\Controllers\SmsTemplateController;
use App\Http\Controllers\PageSettingController;
use App\Http\Controllers\PaymentGateway\CoingateController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\SystemAnalyticsController;
use App\Http\Controllers\TestimonialController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require_once __DIR__ . '/auth.php';
Route::group(['middleware' =>  ['auth', 'Upload', 'verified', 'xss', 'verified_phone']], function () {
    Route::resource('mailtemplate', MailTempleteController::class);
});

Route::group(['middleware' => ['auth', 'xss', 'Setting', 'verified', '2fa', 'verified_phone', 'Upload']], function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('profile', ProfileController::class);
    Route::resource('users', UserController::class)->except(['show']);
    Route::resource('permission', PermissionController::class);
    Route::resource('roles', RoleController::class);
    Route::post('role-permission/{id}', [RoleController::class, 'assignPermission'])->name('roles.permit');
    Route::resource('faqs', FaqController::class);
    Route::resource('module', ModuleController::class);
    Route::resource('poll', PollController::class);
    Route::resource('form-values', FormValueController::class);
    Route::resource('forms', FormController::class)->except(['show']);
    Route::resource('blogs', BlogController::class)->except(['show']);
    Route::resource('blog-category', BlogCategoryController::class);
    Route::post('blogcategory-status/{id}', [BlogCategoryController::class, 'blogCategoryStatus'])->name('blogcategory.status');

    Route::get('forms/add', [FormController::class, 'addForm'])->name('forms.add');
    Route::get('forms/use/template/{id}', [FormController::class, 'useFormtemplate'])->name('forms.use.template');

    //Booking
    Route::resource('bookings', BookingController::class)->except(['show']);;
    Route::get('bookings/design/{id}', [BookingController::class, 'design'])->name('booking.design');
    Route::put('bookings/design/update/{id}', [BookingController::class, 'designUpdate'])->name('booking.design.update');
    Route::get('bookings/slots/setting/{id}', [BookingController::class, 'slotsSetting'])->name('booking.slots.setting');
    Route::post('bookings/slots/setting/update/{id}', [BookingController::class, 'slotsSettingupdate'])->name('booking.slots.setting.update');
    Route::get('bookings/slots/time/appoinment/{id}', [BookingController::class, 'appoinmentTime'])->name('booking.appoinment.time');
    Route::get('bookings/slots/seat/appoinment/{id}', [BookingController::class, 'appoinmentSeat'])->name('booking.appoinment.seat');
    Route::get('bookings/payment/integration/{id}', [BookingController::class, 'bookingpaymentIntegration'])->name('booking.payment.integration');
    Route::post('bookings/payment/integration/store/{id}', [BookingController::class, 'bookingpaymentIntegrationstore'])->name('booking.payment.integration.store');


    Route::get('calendar/bookings', [BookingController::class, 'bookingCalendar'])->name('booking.calendar');


    //booking value
    Route::get('booking-values/{id}/view', [BookingValueController::class, 'showBookingsForms'])->name('view.booking.values');
    Route::get('booking-values/time/{id}/view', [BookingValueController::class, 'timingBookingvaluesShow'])->name('timing.bookingvalues.show');
    Route::get('booking-values/seats/{id}/view', [BookingValueController::class, 'seatsBookingvaluesShow'])->name('seats.bookingvalues.show');
    Route::get('booking-values/{id}/time-booking/edit', [BookingValueController::class, 'timeBookingEdit'])->name('booking.time-bookings.edit');
    Route::get('booking-values/{id}/seats-booking/edit', [BookingValueController::class, 'seatsBookingEdit'])->name('booking.seats-bookings.edit');
    Route::delete('booking-values/{id}/delete', [BookingValueController::class, 'destroy'])->name('bookingvalues.destroy');


    // Form
    Route::group(['prefix' => 'forms'], function () {

        Route::get('themes/{id}', [FormController::class, 'formTheme'])->name('form.theme');
        Route::get('themes/edit/{theme}/{id}', [FormController::class, 'formThemeEdit'])->name('form.theme.edit');
        Route::post('themes/update/{id}', [FormController::class, 'formThemeUpdate'])->name('form.theme.update');
        Route::get('integration/{id}', [FormController::class, 'formIntegration'])->name('form.integration');
        Route::get('payment/integration/{id}', [FormController::class, 'formpaymentIntegration'])->name('form.payment.integration');
        Route::post('payment/integration/store/{id}', [FormController::class, 'formpaymentIntegrationstore'])->name('form.payment.integration.store');
        Route::post('integration/{id}', [FormController::class, 'formIntegrationStore'])->name('form.integration.store');
        Route::post('themes/change/{id}', [FormController::class, 'themeChange'])->name('form.theme.change');

        Route::get('slack/integration/{id}', [FormController::class, 'slackIntegration'])->name('slack.integration');
        Route::get('telegram/integration/{id}', [FormController::class, 'telegramIntegration'])->name('telegram.integration');
        Route::get('mailgun/integration/{id}', [FormController::class, 'mailgunIntegration'])->name('mailgun.integration');
        Route::get('bulkgate/integration/{id}', [FormController::class, 'bulkgateIntegration'])->name('bulkgate.integration');
        Route::get('nexmo/integration/{id}', [FormController::class, 'nexmoIntegration'])->name('nexmo.integration');
        Route::get('fast2sms/integration/{id}', [FormController::class, 'fast2smsIntegration'])->name('fast2sms.integration');
        Route::get('vonage/integration/{id}', [FormController::class, 'vonageIntegration'])->name('vonage.integration');
        Route::get('sendgrid/integration/{id}', [FormController::class, 'sendgridIntegration'])->name('sendgrid.integration');
        Route::get('twilio/integration/{id}', [FormController::class, 'twilioIntegration'])->name('twilio.integration');
        Route::get('textlocal/integration/{id}', [FormController::class, 'textlocalIntegration'])->name('textlocal.integration');
        Route::get('messente/integration/{id}', [FormController::class, 'messenteIntegration'])->name('messente.integration');
        Route::get('smsgateway/integration/{id}', [FormController::class, 'smsgatewayIntegration'])->name('smsgateway.integration');
        Route::get('clicktell/integration/{id}', [FormController::class, 'clicktellIntegration'])->name('clicktell.integration');
        Route::get('clockwork/integration/{id}', [FormController::class, 'clockworkIntegration'])->name('clockwork.integration');

        Route::get('rules/{id}', [FormController::class, 'formRules'])->name('form.rules');
        Route::post('rule/store', [FormController::class, 'storeRule'])->name('rule.store');
        Route::get('rule/{id}/edit', [FormController::class, 'editRule'])->name('rule.edit');
        Route::patch('rule/{id}/update', [FormController::class, 'ruleUpdate'])->name('rule.update');
        Route::delete('rule/{id}/delete', [FormController::class, 'ruleDelete'])->name('rule.delete');
        Route::get('get/rules', [FormController::class, 'getField'])->name('get.field');

        Route::get('grid/{id?}', [FormController::class, 'gridView'])->name('grid.form.view');
        Route::post('status/{id}', [FormController::class, 'formStatus'])->name('form.status');
    });


    //Form Template
    Route::resource('form-template', FormTemplateController::class);
    Route::post('form-template/status/{id}', [FormTemplateController::class, 'status'])->name('formTemplate.status');

resources/views/form/themes/index.blade.php
{!! Form::open([
    'route' => ['form.theme.update', $form->id],
    'method' => 'POST',
    'enctype' => 'multipart/form-data',
    'novalidate',
    'data-validate',
]) !!}
<div class="modal-body">
    <div class="row">
        <div class="col-sm-12">
            {{ Form::hidden('theme', $slug, []) }}
            <div class="form-group d-flex align-items-center row">
                <div class="setting-card setting-logo-box">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <h6 class="mt-2">
                                    <i data-feather="credit-card" class="me-2"></i>{{ __('Primary color settings') }}
                                </h6>
                                <div class="theme-color themes-color">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-1' ? 'active_color' : '' }}"
                                        data-value="theme-1"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-1' ? 'checked' : '' }} name="color" value="theme-1">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-2' ? 'active_color' : '' }}"
                                        data-value="theme-2"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-2' ? 'checked' : '' }} name="color" value="theme-2">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-3' ? 'active_color' : '' }}"
                                        data-value="theme-3"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-3' ? 'checked' : '' }} name="color" value="theme-3">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-4' ? 'active_color' : '' }}"
                                        data-value="theme-4"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-4' ? 'checked' : '' }} name="color" value="theme-4">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-5' ? 'active_color' : '' }}"
                                        data-value="theme-5"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-5' ? 'checked' : '' }} name="color" value="theme-5">
                                    <br>
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-6' ? 'active_color' : '' }}"
                                        data-value="theme-6"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-6' ? 'checked' : '' }} name="color" value="theme-6">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-7' ? 'active_color' : '' }}"
                                        data-value="theme-7"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-7' ? 'checked' : '' }} name="color" value="theme-7">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-8' ? 'active_color' : '' }}"
                                        data-value="theme-8"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-8' ? 'checked' : '' }} name="color" value="theme-8">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-9' ? 'active_color' : '' }}"
                                        data-value="theme-9"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-9' ? 'checked' : '' }} name="color" value="theme-9">
                                    <a href="javascript:void(0);"
                                        class="theme-colors {{ $form->theme_color == 'theme-10' ? 'active_color' : '' }}"
                                        data-value="theme-10"></a>
                                    <input type="radio" class="theme_color d-none" {{ $form->theme_color == 'theme-10' ? 'checked' : '' }} name="color" value="theme-10">
                                </div>
                            </div>
                            @if ($slug == 'theme3')
                                <div class="form-group">
                                    {{ Form::label('background_image', __('Background Image'), ['class' => 'form-label']) }}
                                    {!! Form::file('background_image', ['class' => 'form-control']) !!}
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <div class="float-end">
        {{ Form::button(__('Cancel'), ['class' => 'btn btn-secondary', 'data-bs-dismiss' => 'modal']) }}
        {{ Form::button(__('Save'), ['type' => 'submit', 'class' => 'btn btn-primary', 'data-bs-dismiss' => 'modal', 'id' => 'save-btn']) }}
    </div>
</div>
{!! Form::close() !!}

resources/views/form/themes/theme.blade.php
@extends('layouts.main')
@section('title', __('Theme Setting'))
@section('breadcrumb')
    <div class="col-md-12">
        <div class="d-flex justify-content-between">
            <div class="previous-next-btn">
                <div class="page-header-title">
                    <h4 class="m-b-10">{{ __('Theme Setting') }}</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('Dashboard') }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('forms.index') }}">{{ __('Forms') }}</a></li>
                    <li class="breadcrumb-item"> {{ __('Theme Setting') }} </li>
                </ul>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5>{{ __('Theme Setting') }}</h5>
                </div>
                {!! Form::open([
                    'route' => ['form.theme.change', $form->id],
                    'method' => 'POST',
                    'novalidate',
                    'data-validate',
                ]) !!}
                <div class="card-body">
                    {{ Form::hidden('theme', $form->theme, []) }}
                    <div class="form-group">
                        <label class="form-label">{{ __('Select Themes') }}</label>
                    </div>
                    <div class="uploaded-pics gy-3 row">
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme1' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme1" src="{{ asset('assets/form-themes/theme1/theme1.png') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme1', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme2' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme2" src="{{ asset('assets/form-themes/theme2/theme2.jpg') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme2', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme3' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme3" src="{{ asset('assets/form-themes/theme3/theme3.jpg') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button">
                                    <button data-url="{{ route('form.theme.edit', ['theme3', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme4' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme4" src="{{ asset('assets/form-themes/theme4/theme4.png') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme4', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme5' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme5" src="{{ asset('assets/form-themes/theme5/theme5.png') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme5', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme6' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme6" src="{{ asset('assets/form-themes/theme6/theme6.png') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme6', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme7' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme7" src="{{ asset('assets/form-themes/theme7/theme7.jpg') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme7', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                        <div
                            class="col-lg-3 col-md-4 col-sm-6 theme-view-card {{ $form->theme == 'theme8' ? 'selected-theme' : '' }}">
                            <div class="theme-view-inner theme-view-hover">
                                <div class="theme-view-img">
                                    <img data-id="theme8" src="{{ asset('assets/form-themes/theme8/theme8.jpg') }}">
                                </div>
                                <div class="theme-overlay"></div>
                                <div class="theme-button"><button
                                        data-url="{{ route('form.theme.edit', ['theme8', $form->id]) }}"
                                        class="btn btn-primary btn-sm selectTheme" type="button"><i
                                            class="ti ti-edit"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="text-end">
                        {!! Html::link(route('forms.index'), __('Cancel'), ['class' => 'btn btn-secondary']) !!}
                        {{ Form::button(__('Save'), ['type' => 'submit', 'class' => 'btn btn-primary']) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        $(document).ready(function() {
            $(document).on('click', '.theme-button button.selectTheme', function() {
                var url = $(this).attr('data-url');
                var modal = $('#common_modal');
                $.ajax({
                    type: "GET",
                    url: url,
                    data: {},
                    success: function(response) {
                        modal.find('.modal-title').html('{{ __('Edit Theme') }}');
                        modal.find('.body').html(response);
                        modal.modal('show');
                        modal.find('.theme-colors').click(function() {
                            $('.theme-colors').removeClass('active_color');
                            $(this).addClass('active_color');
                            var val = $(this).attr('data-value');
                            modal.find('input[name="color"]').attr('checked', false);
                            modal.find('input[value="' + val + '"]').attr('checked',
                                true);
                        });
                    },
                    error: function(error) {}
                });
            });
            $(document).on('click', '.theme-view-hover', function() {
                var theme = $(this).find('img').attr('data-id');
                $('input[name="theme"]').val(theme);
                $('.theme-view-card').removeClass('selected-theme');
                $(this).parents('.theme-view-card').addClass('selected-theme');
            });
        });
    </script>
@endpush