routes/web.php
<?php

use App\Http\Controllers\BlogCategoryController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\BookingValueController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\CommentsReplyController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\FormValueController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailTempleteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PollController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\FormCommentsController;
use App\Http\Controllers\FormCommentsReplyController;
use App\Http\Controllers\DashboardWidgetController;
use App\Http\Controllers\DocumentGenratorController;
use App\Http\Controllers\DocumentMenuController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FormTemplateController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\LoginSecurityController;
use App\Http\Controllers\PaymentGateway\MercadoController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\PaymentGateway\MollieController;
use App\Http\Controllers\NotificationsSettingController;
use App\Http\Controllers\PaymentGateway\PaytmController;
use App\Http\Controllers\PaymentGateway\PayUMoneyController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SmsController;
use App\Http\Controllers\SmsTemplateController;
use App\Http\Controllers\PageSettingController;
use App\Http\Controllers\PaymentGateway\CoingateController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\SystemAnalyticsController;
use App\Http\Controllers\TestimonialController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require_once __DIR__ . '/auth.php';
Route::group(['middleware' =>  ['auth', 'Upload', 'verified', 'xss', 'verified_phone']], function () {
    Route::resource('mailtemplate', MailTempleteController::class);
});

Route::group(['middleware' => ['auth', 'xss', 'Setting', 'verified', '2fa', 'verified_phone', 'Upload']], function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::resource('profile', ProfileController::class);
    Route::resource('users', UserController::class)->except(['show']);
    Route::resource('permission', PermissionController::class);
    Route::resource('roles', RoleController::class);
    Route::post('role-permission/{id}', [RoleController::class, 'assignPermission'])->name('roles.permit');
    Route::resource('faqs', FaqController::class);
    Route::resource('module', ModuleController::class);
    Route::resource('poll', PollController::class);
    Route::resource('form-values', FormValueController::class);
    Route::resource('forms', FormController::class)->except(['show']);
    Route::resource('blogs', BlogController::class)->except(['show']);
    Route::resource('blog-category', BlogCategoryController::class);
    Route::post('blogcategory-status/{id}', [BlogCategoryController::class, 'blogCategoryStatus'])->name('blogcategory.status');

    Route::get('forms/add', [FormController::class, 'addForm'])->name('forms.add');
    Route::get('forms/use/template/{id}', [FormController::class, 'useFormtemplate'])->name('forms.use.template');

    //Booking
    Route::resource('bookings', BookingController::class)->except(['show']);;
    Route::get('bookings/design/{id}', [BookingController::class, 'design'])->name('booking.design');
    Route::put('bookings/design/update/{id}', [BookingController::class, 'designUpdate'])->name('booking.design.update');
    Route::get('bookings/slots/setting/{id}', [BookingController::class, 'slotsSetting'])->name('booking.slots.setting');
    Route::post('bookings/slots/setting/update/{id}', [BookingController::class, 'slotsSettingupdate'])->name('booking.slots.setting.update');
    Route::get('bookings/slots/time/appoinment/{id}', [BookingController::class, 'appoinmentTime'])->name('booking.appoinment.time');
    Route::get('bookings/slots/seat/appoinment/{id}', [BookingController::class, 'appoinmentSeat'])->name('booking.appoinment.seat');
    Route::get('bookings/payment/integration/{id}', [BookingController::class, 'bookingpaymentIntegration'])->name('booking.payment.integration');
    Route::post('bookings/payment/integration/store/{id}', [BookingController::class, 'bookingpaymentIntegrationstore'])->name('booking.payment.integration.store');


    Route::get('calendar/bookings', [BookingController::class, 'bookingCalendar'])->name('booking.calendar');


    //booking value
    Route::get('booking-values/{id}/view', [BookingValueController::class, 'showBookingsForms'])->name('view.booking.values');
    Route::get('booking-values/time/{id}/view', [BookingValueController::class, 'timingBookingvaluesShow'])->name('timing.bookingvalues.show');
    Route::get('booking-values/seats/{id}/view', [BookingValueController::class, 'seatsBookingvaluesShow'])->name('seats.bookingvalues.show');
    Route::get('booking-values/{id}/time-booking/edit', [BookingValueController::class, 'timeBookingEdit'])->name('booking.time-bookings.edit');
    Route::get('booking-values/{id}/seats-booking/edit', [BookingValueController::class, 'seatsBookingEdit'])->name('booking.seats-bookings.edit');
    Route::delete('booking-values/{id}/delete', [BookingValueController::class, 'destroy'])->name('bookingvalues.destroy');


    // Form
    Route::group(['prefix' => 'forms'], function () {

        Route::get('themes/{id}', [FormController::class, 'formTheme'])->name('form.theme');
        Route::get('themes/edit/{theme}/{id}', [FormController::class, 'formThemeEdit'])->name('form.theme.edit');
        Route::post('themes/update/{id}', [FormController::class, 'formThemeUpdate'])->name('form.theme.update');
        Route::get('integration/{id}', [FormController::class, 'formIntegration'])->name('form.integration');
        Route::get('payment/integration/{id}', [FormController::class, 'formpaymentIntegration'])->name('form.payment.integration');
        Route::post('payment/integration/store/{id}', [FormController::class, 'formpaymentIntegrationstore'])->name('form.payment.integration.store');
        Route::post('integration/{id}', [FormController::class, 'formIntegrationStore'])->name('form.integration.store');
        Route::post('themes/change/{id}', [FormController::class, 'themeChange'])->name('form.theme.change');

        Route::get('slack/integration/{id}', [FormController::class, 'slackIntegration'])->name('slack.integration');
        Route::get('telegram/integration/{id}', [FormController::class, 'telegramIntegration'])->name('telegram.integration');
        Route::get('mailgun/integration/{id}', [FormController::class, 'mailgunIntegration'])->name('mailgun.integration');
        Route::get('bulkgate/integration/{id}', [FormController::class, 'bulkgateIntegration'])->name('bulkgate.integration');
        Route::get('nexmo/integration/{id}', [FormController::class, 'nexmoIntegration'])->name('nexmo.integration');
        Route::get('fast2sms/integration/{id}', [FormController::class, 'fast2smsIntegration'])->name('fast2sms.integration');
        Route::get('vonage/integration/{id}', [FormController::class, 'vonageIntegration'])->name('vonage.integration');
        Route::get('sendgrid/integration/{id}', [FormController::class, 'sendgridIntegration'])->name('sendgrid.integration');
        Route::get('twilio/integration/{id}', [FormController::class, 'twilioIntegration'])->name('twilio.integration');
        Route::get('textlocal/integration/{id}', [FormController::class, 'textlocalIntegration'])->name('textlocal.integration');
        Route::get('messente/integration/{id}', [FormController::class, 'messenteIntegration'])->name('messente.integration');
        Route::get('smsgateway/integration/{id}', [FormController::class, 'smsgatewayIntegration'])->name('smsgateway.integration');
        Route::get('clicktell/integration/{id}', [FormController::class, 'clicktellIntegration'])->name('clicktell.integration');
        Route::get('clockwork/integration/{id}', [FormController::class, 'clockworkIntegration'])->name('clockwork.integration');

        Route::get('rules/{id}', [FormController::class, 'formRules'])->name('form.rules');
        Route::post('rule/store', [FormController::class, 'storeRule'])->name('rule.store');
        Route::get('rule/{id}/edit', [FormController::class, 'editRule'])->name('rule.edit');
        Route::patch('rule/{id}/update', [FormController::class, 'ruleUpdate'])->name('rule.update');
        Route::delete('rule/{id}/delete', [FormController::class, 'ruleDelete'])->name('rule.delete');
        Route::get('get/rules', [FormController::class, 'getField'])->name('get.field');

        Route::get('grid/{id?}', [FormController::class, 'gridView'])->name('grid.form.view');
        Route::post('status/{id}', [FormController::class, 'formStatus'])->name('form.status');
    });


    //Form Template
    Route::resource('form-template', FormTemplateController::class);
    Route::post('form-template/status/{id}', [FormTemplateController::class, 'status'])->name('formTemplate.status');

app/Http/Controllers/MailTempleteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\DataTables\MailTempleDataTable;
use Spatie\MailTemplates\Models\MailTemplate;

class MailTempleteController extends Controller
{
    public function index(MailTempleDataTable $dataTable)
    {
        if (\Auth::user()->can('manage-mailtemplate')) {
            return $dataTable->render('mailtemplete.index');
        } else {
            return redirect()->back()->with('failed', __('Permission denied.'));
        }
    }

    public function create()
    {
        if (\Auth::user()->can('create-mailtemplate')) {
            return view('mailtemplete.create');
        } else {
            return redirect()->back()->with('failed', __('Permission denied.'));
        }
    }

    public function store(Request $request)
    {
        if (\Auth::user()->can('create-mailtemplate')) {
            request()->validate([
                'mailable' => 'required',
                'subject' => 'required',
                'html_template' => 'required',
            ]);
            MailTemplate::create(['mailable' => $request->mailable, 'subject' => $request->subject, 'html_template' => $request->html_template]);
            return redirect()->route('mailtemplate.index')
                ->with('success', __('Email templete created successfully.'));
        } else {
            return redirect()->back()->with('failed', __('Permission denied.'));
        }
    }

    public function edit($id)
    {
        if (\Auth::user()->can('edit-mailtemplate')) {
            $mailtemplate = Mailtemplate::find($id);
            return view('mailtemplete.edit', compact('mailtemplate'));
        } else {
            return redirect()->back()->with('failed', __('Permission denied.'));
        }
    }

    public function update(Request $request, $id)
    {
        if (\Auth::user()->can('edit-mailtemplate')) {
            request()->validate([
                'mailable' => 'required',
                'subject' => 'required',
                'html_template' => 'required',
            ]);
            $mailtemplete = Mailtemplate::find($id);
            $mailtemplete->mailable = $request->mailable;
            $mailtemplete->subject = $request->subject;
            $mailtemplete->html_template = $request->html_template;
            $mailtemplete->update();
            return redirect()->route('mailtemplate.index')->with('success', __('Email templete updated successfully.'));
        } else {
            return redirect()->back()->with('failed', __('Permission denied.'));
        }
    }

    public function destroy($id)
    {
        if (\Auth::user()->can('delete-mailtemplate')) {
            $mailtemplete = Mailtemplate::find($id);
            $mailtemplete->delete();
            return redirect()->route('mailtemplate.index')->with('success', __('Email template deleted successfully.'));
        } else {
            return redirect()->back()->with('failed', __('Permission denied.'));
        }
    }
}

resources/views/mailtemplete/action.blade.php
@can('edit-mailtemplate')
    <a href="{{ route('mailtemplate.edit', $mailtemple->id) }}" class="btn btn-primary btn-sm" data-toggle="tooltip"
        data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-original-title="{{ __('Edit') }}"><i
            class="ti ti-edit"></i> </a>
@endcan

resources/views/mailtemplete/create.blade.php
@extends('layouts.main')
@section('title', __('Create Mail Template'))
@section('breadcrumb')
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h4 class="m-b-10">{{ __('Create Mail Template') }}</h4>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item">{!! Html::link(route('home'), __('Dashboard'), []) !!}</li>
                        <li class="breadcrumb-item">{!! Html::link(route('mailtemplate.index'), __('Mail Templates'), []) !!}</li>
                        <li class="breadcrumb-item active">{{ __('Create Mail Template') }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="layout-px-spacing row">
        <div id="basic" class="mx-auto col-lg-6 layout-spacing">
            <div class="statbox card box box-shadow">
                <div class="card-header">
                    <h5>{{ __('Create Mail Template') }}</h5>
                </div>
                {!! Form::open(['route' => 'mailtemplate.store', 'method' => 'Post','data-validate' ]) !!}
                <div class="card-body">
                    <div class="row">
                        <div class="mx-auto col-lg-12 col-12">
                            <div class="form-group">
                                {{ Form::label('mailable', __('Mailable'), ['class' => 'form-label']) }}
                                {!! Form::text('mailable', null, ['placeholder' => 'App\Mail\TestMail', 'class' => 'form-control', 'required']) !!}
                            </div>
                            <div class="form-group">
                                {{ Form::label('subject', __('Subject'), ['class' => 'form-label']) }}
                                {!! Form::text('subject', null, [
                                    'placeholder' => 'readonly',
                                    'class' => 'form-control',
                                    'required',
                                ]) !!}
                            </div>
                            <div class="form-group">
                                {{ Form::label('html_template', __('Html Template'), ['class' => 'form-label']) }}
                                {!! Form::textarea('html_template', null, [
                                    'placeholder' => 'Enter html template',
                                    'class' => 'form-control',
                                    'required',
                                ]) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="float-end">
                        {!! Html::link(route('mailtemplate.index'), __('Cancel'), ['class'=>'btn btn-secondary']) !!}
                        {{ Form::button(__('Save'),['type' => 'submit','class' => 'btn btn-primary']) }}
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        CKEDITOR.replace('html_template', {
            filebrowserUploadUrl: "{{ route('ckeditor.upload', ['_token' => csrf_token()]) }}",
            filebrowserUploadMethod: 'form'
        });
    </script>
@endpush

resources/views/mailtemplete/edit.blade.php
@extends('layouts.main')
@section('title', __('Edit Email Template'))
@section('breadcrumb')
    <div class="col-md-12">
        <div class="page-header-title">
            <h4 class="m-b-10">{{ __('Edit Email Template') }}</h4>
        </div>
        <ul class="breadcrumb">
            <li class="breadcrumb-item">{!! Html::link(route('home'), __('Dashboard'), []) !!}</li>
            <li class="breadcrumb-item">{!! Html::link(route('mailtemplate.index'), __('Email Templates'), []) !!} </li>
            <li class="breadcrumb-item active">{{ __('Edit Email Template') }}</li>
        </ul>
    </div>
@endsection
@section('content')
    <div class="layout-px-spacing row">
        <div id="basic" class="mx-auto col-lg-6 layout-spacing">
            <div class="statbox card box box-shadow">
                <div class="card-header">
                    <h5>{{ __('Edit Email Template') }}</h5>
                </div>
                {!! Form::model($mailtemplate, [
                    'route' => ['mailtemplate.update', $mailtemplate->id],
                    'method' => 'PUT',
                    'data-validate',
                ]) !!}
                <div class="card-body">
                    <div class="row">
                        <div class="mx-auto col-lg-12 col-12">
                            <div class="form-group">
                                {{ Form::label('variables', __('Variables ;'), ['class' => 'form-label fw-bolder text-dark fs-6']) }}
                                @foreach ($mailtemplate->variables as $variables)
                                    <span class="fw-bolder text-dark fs-6">{{ <?php echo $variables; ?> }}</span>
                                @endforeach
                            </div>
                            <div class="form-group">
                                {{ Form::label('mailable', __('Mailable'), ['class' => 'form-label']) }}
                                {!! Form::text('mailable', null, ['placeholder' => 'App\Mail\TestMail', 'class' => 'form-control', 'readonly']) !!}
                            </div>
                            <div class="form-group">
                                {{ Form::label('subject', __('Subject'), ['class' => 'form-label']) }}
                                {!! Form::text('subject', null, [
                                    'placeholder' => 'readonly',
                                    'class' => 'form-control',
                                ]) !!}
                            </div>
                            <div class="form-group">
                                {{ Form::label('html_template', __('Html Template'), ['class' => 'form-label']) }}
                                {!! Form::textarea('html_template', null, [
                                    'placeholder' => '',
                                    'class' => 'form-control',
                                ]) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="text-end">
                        {!! Html::link(route('mailtemplate.index'), __('Cancel'), ['class' => 'btn btn-secondary']) !!}
                        {{ Form::button(__('Save'), ['type' => 'submit','class' => 'btn btn-primary']) }}
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection
@push('script')
<script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('html_template', {
            filebrowserUploadUrl: "{{ route('ckeditor.upload', ['_token' => csrf_token()]) }}",
            filebrowserUploadMethod: 'form'
        });
    </script>
@endpush

resources/views/mailtemplete/index.blade.php
@extends('layouts.main')
@section('title', __('Email Templates'))
@section('breadcrumb')
    <div class="col-md-12">
        <div class="page-header-title">
            <h4 class="m-b-10">{{ __('Email Templates') }}</h4>
        </div>
        <ul class="breadcrumb">
            <li class="breadcrumb-item">{!! Html::link(route('home'), __('Dashboard'), []) !!}</li>
            <li class="breadcrumb-item active">{{ __('Email Templates') }} </li>
        </ul>
    </div>
@endsection
@section('content')
<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body table-border-style">
                <div class="table-responsive">
                    {{ $dataTable->table(['width' => '100%']) }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('style')
    @include('layouts.includes.datatable-css')
@endpush
@push('script')
    @include('layouts.includes.datatable-js')
    {{ $dataTable->scripts() }}
@endpush